#!/bin/sh
# A fuzzy file-finder and opener based on dmenu
# Requires: dmenu, xdg-utils
# Just a modification of these scripts:
# https://gist.github.com/dragonauta/6161b40ff0236ed96d7ff56639ac538d
# https://github.com/Chrysostomus/bspwm-scripts/blob/master/bin/finder
# The folders variable can be changed to fit your needs an easy one would be ~/
# The -L argument is only needed if you want to follow symlinks if not you can remove it
# Some modification:
# add -type f after the $folders variable if you want to search only for files
# add -type d after the $folders variable if you want to search only for directories
# add regular expressions to filter eg.: \( ! -regex '.*/\..*' \) to filter .dotfiles
# add -r after xargs to avoid opening evince when no file is selected

LINES=20
FOLDERS="$HOME/Dropbox $HOME/Documents"
HEIGHT=20

## define the font for dmenu to be used
DMENU_FN="Noto-11"

## background colour for unselected menu-items
DMENU_NB="#4C566A"

## textcolour for unselected menu-items
DMENU_NF="#D8DEE9"

## background colour for selected menu-items
DMENU_SB="#81A1C1"

## textcolour for selected menu-items
DMENU_SF="#D8DEE9"

## export our variables
DMENU_OPTIONS="-i -h $HEIGHT -l $LINES -fn $DMENU_FN -nb $DMENU_NB -nf $DMENU_NF -sf $DMENU_SF -sb $DMENU_SB"

# find -L $FOLDERS -name *.pdf | sed 's/ /\\ /g' | sort -f | dmenu $DMENU_OPTIONS | xargs -r evince

find -L $FOLDERS -name *.pdf | sed 's/ /\\ /g' | sort -f | dmenu $DMENU_OPTIONS | xargs -r zathura
