#!/bin/sh
# This script is used to reset keymaps to the original state.
# Increase key speed via a rate change
xset r rate 300 50
xmodmap $HOME/.scripts/tkconf/.Xmodmap-original-t440p
killall xcape 2>/dev/null
