#!/bin/sh
# This script is called by i3 upon startup to remap keys
# Increase key speed via a rate change
xset r rate 300 50
xmodmap $HOME/.xmodmaprc-t440p
killall xcape 2>/dev/null
xcape -t 10000 -e "Control_R=Return;Control_L=Escape;Hyper_L=Tab;Hyper_R=backslash"
